# 更新服务器的地址，注意仅能指向目录
# 可以写成列表的形式来使用多个备用源
# 支持http(s)源和sftp源(sftp源的用法请翻到文件末尾)
#
#   http(s)源例子：
#     1. https://127.0.0.1:6600  （默认形式）
#     2. https://127.0.0.1:6600/subfolder  （子目录形式，末尾不要加斜线）
#
server: http://127.0.0.1:6600

# 是否禁用界面主题
# true: 禁用界面主题，可以解决窗口出现无响应的问题！
# false: 不会禁用界面主题，运行在某些机器上时可能会出现窗口出现无响应的问题！
disable-theme: true

# 更新完是否自动退出，默认值false（默认不开启此选项）
# true: 更新完后会自动关闭窗口
# false: 更新完后需要点击“确定”对话框退出程序
auto-exit: false

# 安静模式（默认不开启此选项）
# true: 程序启动后不显示窗口，会在后台静默检查文件更新，如果没有更新就直接启动Minecraft，
#       如果有更新再显示下载进度条窗口，此选项可以尽可能将更新助手的存在感降低（只在下载文件时显示窗口）
# false: 程序启动后每次都显示窗口，并在窗口中显示检查文件的进度和下载文件的进度，一切妥当后启动Minecraft
# 此选项仅仅当程序以图型界面模式启动时有效
quiet-mode: false

# 更新时如果发生错误（尤其是网络原因）时，是否继续进入游戏，而不是使游戏崩溃（默认不开启此选项）
# true: 如果更新发生错误，继续启动Minecraft游戏
# false：如果更新发生错误，强制使Minecraft崩溃，停止启动过程
# 如果需要区分是更新问题还是游戏本身的问题，请查看游戏启动日志
# 此选项仅当程序以JavaAgent模式（非图形模式）启动时有效
no-throwing: false

# 存储当前版本号的文件（一般无需修改此选项）
# 起始目录为程序Jar文件所在目录
# version-file: mc-patch-version.txt

# 显式指定“更新起始目录”，默认值是空字符串""（一般无需修改此选项）
# 实际文件更新的起始目录 = 工作目录 + base-path
# 1.如果base-path被设置为'.'可以强制指定当前工作目录为更新起始目录并禁用.minecraft目录搜索
# 2.如果base-path被设置为../，这样就可以更新工作目录的上级目录了
# 3.如果base-path被设置为.minecraft222/，这样所有文件就会被更新到.minecraft222里
# 如果此选项被注释或者为空字符串''，程序会自动寻找最近的.minecraft目录的父目录作为更新起始路径
# 如果此选项未被注释，则会禁用自动搜寻.minecraft的功能。
# base-path: ''

# 全局http连接超时（单位毫秒，仅对http源有效）
# http-connect-timeout: 3000

# 全局http读取超时（单位毫秒，仅对http源有效）
# http-read-timeout: 50000

# 全局http写入超时（单位毫秒，仅对http源有效）
# http-write-timeout: 3000

# 出现网络问题时的重试次数（仅对http源有效）
# retry-times: 3

#   sftp源例子： （一般情况下不建议使用sftp更新源，如果处理不好可能会有服务器安全隐患）
#     1. sftp://user:pass:f0:91:07:33:28:19:c5:2c:ea:e4:a9:2b:41:ce:3d:63@192.168.5.133:22/  （默认形式，工作目录本身）
#     2. sftp://user:pass:f0:91:07:33:28:19:c5:2c:ea:e4:a9:2b:41:ce:3d:63@192.168.5.133:22/mm  （相对目录形式，末尾无斜线）
#     3. sftp://user:pass:f0:91:07:33:28:19:c5:2c:ea:e4:a9:2b:41:ce:3d:63@192.168.5.133:22//mm  （绝对目录形式，末尾无斜线）
#       说明: user是用户名，pass是密码，仅支持密码验证
#            f0:91:07:33:28:19:c5:2c:ea:e4:a9:2b:41:ce:3d:63是远程主机指纹
#            192.168.5.132是主机地址，22是端口（端口不能省略） mm是子目录
#            主机指纹支持以下格式
#              1. SHA1:2Fo8c/96zv32xc8GZWbOGYOlRak=  （sha1指纹格式）
#              2. SHA256:oQGbQTujGeNIgh0ONthcEpA/BHxtt3rcYY+NxXTxQjs=  （sha256指纹格式）
#              3. MD5:d3:5e:40:72:db:08:f1:6d:0c:d7:6d:35:0d:ba:7c:32  （md5十六进制冒号分隔形式）
#              4. d3:5e:40:72:db:08:f1:6d:0c:d7:6d:35:0d:ba:7c:32  （base64编码过的sha1指纹格式或者sha256指纹格式）