# 更新服务器的地址，注意仅能指向目录。可以写成列表的形式来使用多个备用源
# 目前支持McPatch客户端支持这三种服务器源：http源、webdav源、sftp源
#
#   http源例子：
#     1. http://127.0.0.1:6600  （默认形式，http协议）
#     2. https://127.0.0.1:6600/subfolder  （子目录形式，末尾不要加斜线，https协议）
#
#   webdav源：（webdav源的格式和http源很相似，注意webdav代表http，webdavs代表https，这样写是为了和http源做区分）
#     1. webdav://user:pass:127.0.0.1:80 （默认形式，webdav使用http协议）
#     2. webdavs://user:pass:127.0.0.1:443/subfolder （子目录形式，webdav使用https协议，注意https默认端口为443，而非80）
#        说明: user是用户名，pass是密码，均不可省略，127.0.0.1是主机地址，80和443是端口（端口不可省略），subfolder是可选的子目录
#
#   sftp源例子： （一般情况下不建议使用sftp更新源，如果处理不好可能会有服务器安全隐患）
#     1. sftp://user:pass:f0:91:07:33:28:19:c5:2c:ea:e4:a9:2b:41:ce:3d:63@192.168.5.133:22/  （默认形式，工作目录本身）
#     2. sftp://user:pass:f0:91:07:33:28:19:c5:2c:ea:e4:a9:2b:41:ce:3d:63@192.168.5.133:22/subfolder  （相对目录形式，末尾无斜线）
#     3. sftp://user:pass:f0:91:07:33:28:19:c5:2c:ea:e4:a9:2b:41:ce:3d:63@192.168.5.133:22//subfolder  （绝对目录形式，末尾无斜线）
#        说明: user是用户名，pass是密码，仅支持密码验证，f0:91到3d:63是远程主机指纹，192.168.5.132是主机地址，22是端口，subfolder是可选的子目录
#        主机指纹支持以下格式（建议首次配置指纹随便写，然后从报错日志里复制出主机的指纹，这样比亲自去查主机指纹要快）
#          1. SHA1:2Fo8c/96zv32xc8GZWbOGYOlRak=  （sha1指纹格式）
#          2. SHA256:oQGbQTujGeNIgh0ONthcEpA/BHxtt3rcYY+NxXTxQjs=  （sha256指纹格式）
#          3. MD5:d3:5e:40:72:db:08:f1:6d:0c:d7:6d:35:0d:ba:7c:32  （md5十六进制冒号分隔形式）
#          4. d3:5e:40:72:db:08:f1:6d:0c:d7:6d:35:0d:ba:7c:32  （base64编码过的sha1指纹格式或者sha256指纹格式）
#
server: http://127.0.0.1:6600

# 指定UA，一般情况下无需填写。
client-ua: McPatchClient

# 是否禁用界面主题
# true: 禁用界面主题，可以解决窗口出现无响应的问题！
# false: 不会禁用界面主题，运行在某些机器上时可能会出现窗口出现无响应的问题！
disable-theme: false

# 是否在没有任何更新时，显示暂无更新的对话框（通常是：资源文件暂无更新!）
# true：更新完成后会显示“暂无更新”的对话框，需要手点确定
# false：更新完成后会自动退出，无需手动操作
# 本地调试环境建议开启，线上环境建议关闭。当quiet-mode开启时，本设置会被强制覆盖为false，无法变更。
show-finish-message: true

# 是否显示更新记录
# true：每次更新完后都会弹出窗口显示更新记录
# false：更新完成后不会弹出更新记录窗口而是继续下载下一个更新
show-changelogs-message: true

# 安静模式（默认不开启此选项）
# true: 程序启动后不显示窗口，会在后台静默检查文件更新，如果没有更新就直接启动Minecraft，
#       如果有更新再显示下载进度条窗口，此选项可以尽可能将更新助手的存在感降低（只在下载文件时显示窗口）
# false: 程序启动后每次都显示窗口，并在窗口中显示检查文件的进度和下载文件的进度，一切妥当后启动Minecraft
# 此选项仅仅当程序以图型界面模式启动时有效
# 本地调试环境建议关闭，线上环境建议开启
quiet-mode: false

# 更新时如果发生错误（尤其是网络原因）时，是否继续进入游戏，而不是使游戏崩溃（默认不开启此选项）
# true: 如果更新发生错误，继续启动Minecraft游戏
# false：如果更新发生错误，强制使Minecraft崩溃，停止启动过程
# 如果需要区分是更新问题还是游戏本身的问题，请查看游戏启动日志
# 此选项仅当程序以JavaAgent模式（非图形模式）启动时有效
no-throwing: false

# 全局http连接超时（单位毫秒，仅对http源有效）
http-connect-timeout: 3000

# 全局http响应超时（单位毫秒，仅对http源有效）
http-response-timeout: 5000

# 出现网络问题时的重试次数（仅所有源有效）
retry-times: 5

# 存储当前版本号的文件（一般无需修改此选项）
# 起始目录为程序Jar文件所在目录
version-file: mc-patch-version.txt

# 显式指定“更新起始目录”，默认值是空字符串""（一般无需修改此选项）
# 实际文件更新的起始目录 = 工作目录 + base-path
# 1.如果base-path被设置为'.'可以强制指定当前工作目录为更新起始目录并禁用.minecraft目录搜索
# 2.如果base-path被设置为../，这样就可以更新工作目录的上级目录了
# 3.如果base-path被设置为.minecraft222/，这样所有文件就会被更新到.minecraft222里
# 如果此选项被注释或者为空字符串''，程序会自动寻找最近的.minecraft目录的父目录作为更新起始路径
# 如果此选项未被注释，则会禁用自动搜寻.minecraft的功能。
# 如您使用版本隔离，此处推荐填写'.'
base-path: ''
